on:
  workflow_dispatch:
jobs:
  codex-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Make sure key is set
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ OPENAI_API_KEY is not set"
            exit 1
          else
            echo "✅ OPENAI_API_KEY is set"
          fi
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Codex CLI
        run: |
          npm install -g @openai/codex
          codex --version
          codex exec --full-auto --skip-git-repo-check "Put a description of this repo's purpose into PURPOSE.md"
          cat PURPOSE.md
