on:
  workflow_dispatch:

jobs:
  codex-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.CODEX_API_KEY }}
      CODEX_QUIET_MODE: 1
    steps:
      - name: Make sure key is set
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ OPENAI_API_KEY is not set"
          else
            echo "✅ OPENAI_API_KEY is set"
          fi
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Codex CLI
        run: npm install -g @openai/codex
      - name: Check Codex CLI version
        run: codex --version
      - name: Test codex
        run: codex "Give a brief description of what this repository does"
